# -*- coding: utf-8 -*-
"""AIML LABSHEET 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ijsxu9hpoa7VtUEXWjactpeU_CxC2LoC
"""

#1d array
import numpy as np
A1=np.array([1,2,3,4])
print(A1)

type(A1)

A1.shape

#2d array
A2=np.array([[1,2,3,4],[5,6,7,8]])
print(A2)

type(A2)

A2.shape

#3d array
A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)
type(A3)
A3.shape

import numpy as np
z1=np.zeros(3)
z1

z1=np.zeros(3,dtype=int)
z1

z1.shape

z1.size

z1.ndim

type(z1)

z2=np.zeros((3,4))
z2

z2=np.zeros((3,4),dtype=int)
z2

type(z2)

z2.ndim

z3=np.zeros((2,3,4))
z3

z3.shape
z3.ndim

type(z3)

z3=np.zeros((3,4),dtype=int)
z3

z3.shape

z3.size

z3.ndim

import numpy as np
a1=np.ones(3)
a1

a1=np.ones(3,dtype=int)
a1

a1.size

a1.ndim

a2=np.ones([3,4],dtype=int)
a2

type(a2)

a2.shape

a3=np.ones([4,2,3])
a3

type(a3)

f1=np.full(3,9)
f1

f1=np.full(3,9,dtype=float)
f1



f2=np.full((9,2,3),9)
f2

